### PR TITLE
Fixes compilation errors caused by VarTypes 0.8 and changes some constants according to new RoboCup SSL rules (2015)

### PR DESCRIPTION
**Pull request by hbritto**

### CODE REVIEW

**Comment by mahi97** [comment]
I just test this pull request, but can't build the project, i think the problem was because of protobuf changes.
So I modified "addFieldLine" and "addFieldArc" functions and it work correctly.
the changed is mentioned in "Files changed".

**Comment by mani-monaj** [comment]
@hbritto Thank you for this fixes.
@mahi97 Thank you for taking the time to review/test this. Is it good to merge?

**Comment by mahi97** [comment]
According to my experiment, it worked okey and have some improvements. so i think it's okey to be merged.

**Comment by mani-monaj** [comment]
Thank you @mahi97  and @hbritto. I will merge this. Some exciting new changes are coming to grSim. We will update the CHANGELOG and AUTHORS files very soon.

**Comment by mahi97** [comment]
@hbritto Please give me your university name and a email address for adding this contact info into authors.

**Comment by hbritto** [comment]
Hi, I study at Universidade de São Paulo, and my email address is henrique.menezes@usp.br
Thank you!

**Comment by mani-monaj** [comment]
Thanks @hbritto .

**Pull request merged**
