### PR TITLE
4 Cameras functionality

### PR DESCRIPTION
**Pull request by hbritto**
Adding four cameras functionality, simulating four different cameras with overlap between packets' boundaries.

### CODE REVIEW

**Comment by mahi97** [comment]
@hbritto Can you fix this conflicts ?

**Comment by mahi97** [comment]
I found a problem after i fix conflict and run this code
we get this error: Sending UDP datagram failed (maybe too large?). Size was: 228 byte(s).
and sometime we get : Sending UDP datagram failed (maybe too large?). Size was: 0 byte(s).

@mani-monaj btw we have 4 cam functionality right now but without overlaps.

**Comment by mani-monaj** [comment]
@mahi97 @hbritto Is implementing overlap as part of the current code base difficult? Can we close this PR and instead add overlap to the existing implementation?

**Comment by hbritto** [comment]
@mani-monaj It shouldn't be too difficult. 
@mahi97 Now that you point it out, I realised that I've always used the software with this, yet never noticed any issues. Maybe some modifications my team made quite some time ago are the cause. 

Anyway, since the four cameras functionality has already been implemented, I suppose this can be closed and the overlap may be added on the current code base.

**Comment by mani-monaj** [comment]
Thanks @hbritto for the update. I will close this issue then. I will create another one for adding the overlap.

**Pull request closed without merging**
